#FROM jenkins/jenkins:alpine

# RUN /usr/local/bin/install-plugins.sh workflow-aggregator 

FROM jenkinsci/blueocean

# USER jenkins

# COPY .ssh /var/jenkins_home/

# COPY jenkins_home/ /var/jenkins_home/

# WORKDIR /var/jenkins_home 

