// <auto-generated />
using HomeBid.Services.Bidding.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Bidding.Service.Infrastructure.Migrations
{
    [DbContext(typeof(BiddingContext))]
    [Migration("20190909130103_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Relational:Sequence:bidding.propertyseq", "'propertyseq', 'bidding', '1', '10', '', '', 'Int64', 'False'");

            modelBuilder.Entity("HomeBid.Services.Bidding.Models.BiddingProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:HiLoSequenceName", "propertyseq")
                        .HasAnnotation("Npgsql:HiLoSequenceSchema", "bidding")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<decimal>("AskingPrice");

                    b.Property<bool>("IsBiddingActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("BiddingProperty","bidding");
                });
#pragma warning restore 612, 618
        }
    }
}
